kind: Pod
apiVersion: v1
metadata:
  name: apple-app
  labels:
    app: apple
  namespace: kpt_test
spec:
  containers:
    - name: apple-app
      image: hashicorp/http-echo
      args:
        - -text=Hello apple
